export const DO_SOMETHING_WEIRD = 'ACTION/DO_SOMETHING_WEIRD'

export const TV_SET_CONNECTIONSTATE = 'ACTION_SET_CONNECTIONSTATE'
export const TV_REQUEST_CONNECT = 'ACTION_REQUEST_CONNECT'
export const TV_SET_PAIRINGKEY = 'ACTION_SET_PAIRINGKEY'
export const TV_SET_CURRENT_CHANNEL = 'ACTION_TV_SET_CURRENT_CHANNEL'
export const TV_REQUEST_GET_CURRENT_CHANNEL =
  'ACTION_TV_REQUEST_GET_CURRENT_CHANNEL'

export const TV_REQUEST_SET_CHANNEL = 'ACTION_TV_REQUEST_SET_CHANNEL'
